import type { BuilderQuestion } from '../types/module';
import { MIN_PRESENT_DAY_AGE, MAX_PRESENT_DAY_AGE } from './ageGuard';
import {
  PERSONALITY_CORE,
  PERSONALITY_TEXTURE,
  PERSONALITY_DRIVE,
  PERSONALITY_VULNERABILITY,
} from './personality';

// Player builder questions. The player builds themselves before building the LI.
// MC questions with optional custom input, plus numeric input for age.
// Personality is four axes. See personality.ts.
export const PLAYER_QUESTIONS: BuilderQuestion[] = [
  {
    kind: 'mc',
    id: 'name',
    prompt: 'Your name',
    options: ['Eda', 'Cora', 'Mira', 'Lena', 'Nora', 'Sera', 'Iris', 'Saskia', 'Ada', 'June'],
    required: true,
    allowCustom: true,
  },
  {
    kind: 'mc',
    id: 'gender',
    prompt: 'Your gender',
    options: ['Female', 'Male', 'Nonbinary'],
    required: true,
  },
  {
    kind: 'number',
    id: 'age',
    prompt: 'Your age',
    min: MIN_PRESENT_DAY_AGE,
    max: MAX_PRESENT_DAY_AGE,
    required: true,
  },
  {
    kind: 'mc',
    id: 'profession',
    prompt: 'What do you do?',
    options: [
      'Journalist',
      'Writer / Author',
      'Photographer',
      'Doctor / Surgeon',
      'Nurse / Medic',
      'Lawyer',
      'Teacher / Professor',
      'Artist',
      'Musician',
      'Architect',
      'Designer',
      'Engineer',
      'Software developer',
      'Bartender',
      'Chef',
      'Bookshop owner',
      'Gallery curator',
      'Florist',
      'Therapist / Psychologist',
      'Student',
      'Unemployed / Between things',
    ],
    required: true,
    allowCustom: true,
  },
  {
    kind: 'mc',
    id: 'hairColor',
    prompt: 'Hair color',
    options: ['Black', 'Dark brown', 'Brown', 'Light brown', 'Blonde', 'Platinum', 'Red', 'Auburn', 'White / Silver', 'Dyed'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'hairLength',
    prompt: 'Hair length',
    options: ['Buzzed / Pixie', 'Short', 'Medium', 'Long', 'Very long'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'eyeColor',
    prompt: 'Eye color',
    options: ['Blue', 'Gray', 'Green', 'Hazel', 'Brown', 'Black', 'Amber', 'Heterochromia'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'height',
    prompt: 'Height',
    options: ['Short', 'Average', 'Tall', 'Very tall'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'bodyType',
    prompt: 'Body type',
    options: ['Petite', 'Slim', 'Athletic', 'Curvy', 'Full-figured', 'Tall and lean'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'tattoos',
    prompt: 'Tattoos',
    options: ['None', 'Some', 'Heavy'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'piercings',
    prompt: 'Piercings',
    options: ['None', 'Minimal', 'Significant'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'styleAesthetic',
    prompt: 'Your style',
    options: ['Gothic', 'Edgy / Alt', 'Refined', 'Bohemian', 'Minimalist', 'Vintage', 'Sporty', 'Classic', 'Casual'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'personalityCore',
    prompt: 'How do you hold yourself?',
    options: [...PERSONALITY_CORE],
    required: true,
  },
  {
    kind: 'mc',
    id: 'personalityTexture',
    prompt: 'How do you show what you feel?',
    options: [...PERSONALITY_TEXTURE],
    required: true,
  },
  {
    kind: 'mc',
    id: 'personalityDrive',
    prompt: 'What drives you?',
    options: [...PERSONALITY_DRIVE],
    required: true,
  },
  {
    kind: 'mc',
    id: 'personalityVulnerability',
    prompt: 'What cracks you?',
    options: [...PERSONALITY_VULNERABILITY],
    required: true,
  },
];
