import type { BuilderQuestion } from '../types/module';
import { MIN_PRESENT_DAY_AGE, MAX_PRESENT_DAY_AGE } from './ageGuard';

// Universal LI questions. Applied to every LI build regardless of archetype/trope/setting.
// Covers basics: gender, age, physical attributes, core personality, private life.
// Archetype and trope modules add their own specific questions on top.
// Name is intentionally archetype-flavored, so it lives in the archetype module.
// Age floor is 20. See ageGuard.ts.
export const UNIVERSAL_QUESTIONS: BuilderQuestion[] = [
  {
    kind: 'mc',
    id: 'gender',
    prompt: 'Gender of your love interest',
    options: ['Male', 'Female', 'Nonbinary'],
    required: true,
  },
  {
    kind: 'number',
    id: 'age',
    prompt: 'How old is he/she/they?',
    min: MIN_PRESENT_DAY_AGE,
    max: MAX_PRESENT_DAY_AGE,
    required: true,
  },
  {
    kind: 'mc',
    id: 'hairColor',
    prompt: 'Hair color',
    options: ['Black', 'Dark brown', 'Brown', 'Light brown', 'Blonde', 'Platinum', 'Red', 'Auburn', 'White / Silver', 'Dyed'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'hairLength',
    prompt: 'Hair length',
    options: ['Buzzed', 'Short', 'Medium', 'Long', 'Very long'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'eyeColor',
    prompt: 'Eye color',
    options: ['Blue', 'Gray', 'Green', 'Hazel', 'Brown', 'Black', 'Amber', 'Heterochromia'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'height',
    prompt: 'Height',
    options: ['Short', 'Average', 'Tall', 'Very tall'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'bodyType',
    prompt: 'Body type',
    options: ['Lean', 'Athletic', 'Muscular', 'Built', 'Lanky', 'Broad'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'facialHair',
    prompt: 'Facial hair (or skip)',
    options: ['Clean shaven', 'Stubble', 'Beard', 'Full beard', 'Goatee', 'Not applicable'],
    required: false,
  },
  {
    kind: 'mc',
    id: 'tattoos',
    prompt: 'Tattoos',
    options: ['None', 'Some', 'Heavy'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'piercings',
    prompt: 'Piercings',
    options: ['None', 'Minimal', 'Significant'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'styleAesthetic',
    prompt: 'Style aesthetic',
    options: ['Gothic', 'Hard rock', 'Street', 'Vintage', 'Military', 'Refined', 'Grunge', 'Artsy', 'Minimalist'],
    required: true,
  },
  {
    kind: 'mc',
    id: 'personalityPrimary',
    prompt: 'Primary personality trait',
    options: [
      'Possessive',
      'Cold',
      'Golden retriever',
      'Morally gray',
      'Emotionally unavailable',
      'Worshipping',
      'Sarcastic',
      'Dominant',
      'Protective',
      'Obsessive',
      'Soft only for you',
      'Intelligent strategist',
      'Traumatized',
      'Flirtatious',
      'Dangerous',
      'Emotionally repressed',
    ],
    required: true,
  },
  {
    kind: 'mc',
    id: 'personalitySecondary',
    prompt: 'Secondary personality trait',
    options: [
      'Possessive',
      'Cold',
      'Golden retriever',
      'Morally gray',
      'Emotionally unavailable',
      'Worshipping',
      'Sarcastic',
      'Dominant',
      'Protective',
      'Obsessive',
      'Soft only for you',
      'Intelligent strategist',
      'Traumatized',
      'Flirtatious',
      'Dangerous',
      'Emotionally repressed',
    ],
    required: true,
  },
  {
    kind: 'mc',
    id: 'privateLife',
    prompt: 'How does he handle himself in private?',
    options: [
      'Sober and disciplined',
      'Social drinker',
      'Struggling with substances',
      'In recovery',
      'Spiritual practice',
      'In therapy',
      'None of the above',
    ],
    required: true,
  },
];
