import type { ArchetypeModule } from '../../types/module';

export const rockstarArchetype: ArchetypeModule = {
  id: 'rockstar',
  label: 'Rockstar / Famous Musician',
  defaultDayToDay:
    'Touring, recording, performing, interviews, photo shoots, songwriting sessions. Time is not his own.',
  defaultStakes:
    'Public scrutiny, career trajectory, label politics, parasocial fans, paparazzi, exposure of private life.',
  defaultEnemies:
    'Rival artists, exploitative label execs, paparazzi, obsessed fans, ex-management, powerbrokers in the industry.',
  powerBaseline:
    'High social capital, significant money, name recognition. Limited privacy. Real power is conditional on continued output.',
  questions: [
    {
      kind: 'mc',
      id: 'genre',
      prompt: 'What does he make?',
      options: [
        'Post-metal',
        'Dark rock',
        'Alt-rock',
        'Industrial',
        'Dark pop',
        'Synthwave',
        'Shoegaze',
        'Hard rock',
        'Metal',
      ],
      required: true,
    },
    {
      kind: 'mc',
      id: 'soloOrBand',
      prompt: 'Solo artist or band frontman?',
      options: ['Solo artist', 'Band frontman'],
      required: true,
    },
    {
      kind: 'mc',
      id: 'fameLevel',
      prompt: 'How famous?',
      options: [
        'Cult niche (devoted fanbase, not mainstream)',
        'Rising (gaining traction, second album just hit)',
        'Arena-level (sells out venues, regular press)',
        'Household name (everyone knows him, magazine covers)',
      ],
      required: true,
    },
    {
      kind: 'mc',
      id: 'publicPersona',
      prompt: 'Public persona',
      options: [
        'Unreachable (rarely speaks, mythical)',
        'Chaotic (unpredictable, wrong-headline famous)',
        'Charming (interviews well, beloved)',
        'Volatile (known for outbursts)',
        'Spiritual (cryptic, references ritual or religion)',
        'Reclusive (lives off-grid between albums)',
      ],
      required: true,
    },
    {
      kind: 'mc',
      id: 'stagePresence',
      prompt: 'Onstage',
      options: [
        'Stripped-down (vulnerable, just him and the song)',
        'Theatrical (costumes, narrative, full production)',
        'Aggressive (physical, confrontational, sweat and noise)',
        'Melancholic (slow burn, audience holds breath)',
      ],
      required: true,
    },
    {
      kind: 'mc',
      id: 'publicPast',
      prompt: 'Has he ever publicly talked about his hometown or past?',
      options: [
        'Never (refuses to address it)',
        'Vague references in interviews',
        'Addressed it directly in a song',
        'Addressed it in an interview',
        'Actively lied about it',
      ],
      required: true,
    },
    {
      kind: 'mc',
      id: 'family',
      prompt: 'Family situation',
      options: [
        'Estranged from family',
        'Close with family',
        'Orphan',
        'Single parent',
        'Dark family backstory (abuse, criminality, scandal)',
      ],
      required: true,
    },
    {
      kind: 'mc',
      id: 'bandName',
      prompt: 'Band or project name (pick one or write your own)',
      options: [
        'Black Salt Liturgy',
        'Hollow Saints',
        'Iron Vesper',
        'The Drowning Hours',
        'Saint Mercer',
        'Wolves in the Static',
        'Cold Cathedral',
        'Veiled',
        'Marrow and Smoke',
        'Last Light',
      ],
      required: true,
      allowCustom: true,
    },
    {
      kind: 'mc',
      id: 'name',
      prompt: 'His name (pick one or write your own)',
      options: [
        'Roman Vail',
        'Cassian Wolfe',
        'Atlas Voss',
        'Sebastian Cross',
        'Killian Reyes',
        'Silas Black',
        'Dorian Frost',
        'Theo Ashbury',
        'Nico Marchetti',
        'Wren Halloway',
      ],
      required: true,
      allowCustom: true,
    },
  ],
};
